create table if not exists public.leads (
 id bigint generated by default as identity primary key,
 name text not null,
 phone text not null,
 email text,
 service text not null,
 message text,
 status text not null default 'New',
 created_at timestamptz not null default now()
);
alter table public.leads enable row level security;
-- The website writes through the server using the service-role key.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser.
